version: "2"
services:
  pg:
    image: postgres
    environment:
      - POSTGRES_USER=enes
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=chat
  server:
    build: .
    ports:
      - "1234:1234"
    depends_on:
      - pg
    command: sh -c "/wait && /bin/chat-server"
    environment:
          - WAIT_HOSTS=pg:5432
          - WAIT_HOSTS_TIMEOUT=300
          - WAIT_SLEEP_INTERVAL=30
          - WAIT_HOST_CONNECT_TIMEOUT=30